version: '3.4'

services:
  postgres:
    image: 'postgres'
    container_name: 'postgres'
    restart: unless-stopped
    environment:
      - POSTGRES_DB=auctions-stats
      - POSTGRES_PASSWORD=admin
      - POSTGRES_USER=admin
      - PGDATA=/var/lib/postgresql/data
    ports:
      - '5432:5432'
  pgadmin:
    image: 'dpage/pgadmin4'
    container_name: 'pgadmin'
    restart: unless-stopped
    environment:
       - PGADMIN_DEFAULT_EMAIL=admin@example.com
       - PGADMIN_DEFAULT_PASSWORD=admin

    ports:
      - '15432:80'

