// <auto-generated />
using System;
using AuctionsStats.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace AuctionsStats.Data.Migrations
{
    [DbContext(typeof(AppDataContext))]
    [Migration("20230108155418_InitialSchema")]
    partial class InitialSchema
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.1")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("AuctionsStats.Data.Coin", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("ID");

                    b.Property<string>("Currency")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("CURRENCY");

                    b.Property<DateTime>("LastModified")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("LAST_MODIFIED");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("NAME");

                    b.Property<string>("Nominal")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("NOMINAL");

                    b.Property<string>("ReferenceNo")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("REFERENCE_NO");

                    b.Property<int?>("Year")
                        .HasColumnType("integer")
                        .HasColumnName("ISSUE_YEAR");

                    b.HasKey("Id");

                    b.ToTable("COINS");
                });
#pragma warning restore 612, 618
        }
    }
}
